Feat/register --> reset password, resend verify link, and register fail endpoints
hack-the-6ix/next.api.hackthe6ix.com pull request #4
Opened 2024-03-24 05:40 UTC by Lindsay-X

reset password flow similar to: https://www.checklist.design/flows/password

2024-03-24 21:53 UTC, fpunny commented on src/resources/auth/auth.controller.ts
> +  @Post('verify')
Bit of a nit, but i would prefer if the routes can be a separated by resources a little bit better...

for example we can so something like
`reset-password` and `reset-password/verify` so that its clear that they are somewhat related to each other

2024-03-24 21:55 UTC, fpunny commented on src/resources/auth/auth.controller.ts
> +  @Post('register-fail')
I'm not sure if I understand why we have an endpoint for when registering a user an already exist since that clearly shows that we are treating users differently based on some kind of state.

This conditional logic should live in the register endpoint

2024-03-24 21:56 UTC, fpunny commented on src/resources/auth/auth.controller.ts
> +  @Post('register-fail')
This is a big red flag for security

2024-03-24 21:57 UTC, fpunny commented on src/resources/auth/auth.service.ts
> +    const user = await this.prisma.basicAuth.findUnique({
This looks very similar to the register logic, lets "DRY" up our code a little bit since this is not very nice to maintain

2024-03-24 21:58 UTC, fpunny requested changes
A few code smells, would be nice to get them touched up

2024-03-24 23:33 UTC, Lindsay-X commented on src/resources/auth/auth.controller.ts
> +  @Post('register-fail')
how would I check which kind of error the register endpoint throws? I was struggling on that and decided to make a separate endpoint for fail status code 500

2024-03-26 06:46 UTC, fpunny commented on src/resources/auth/auth.service.ts
> +        audience: [`${aud}`],
nit: the string interpolation is unnessary

2024-03-26 06:47 UTC, fpunny commented on src/resources/auth/auth.service.ts
> +    await this.mailer.send(email, `${subject}`, `${body} ${verifyUrl}`);
nit: string interpolation is not needed

2024-03-26 06:48 UTC, fpunny commented on src/resources/auth/auth.service.ts
> +    const user = await this.prisma.basicAuth.findUnique({
Hmm I find the findUniqueOrThrow wrapped cleaner since then u don't force everything to throw notfoundexception when not needed. But this would do

2024-03-26 07:14 UTC, fpunny approved these changes
LGTM

2024-03-26 07:14 UTC, merged